apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.name}}-api
  description: The swagger API definition of ${{values.name}} service.

spec:
  type: openapi
  lifecycle: production
  owner: ${{values.owner}}
  definition: |
    openapi: "3.0.0"
    paths:
      /health:
        get:
          operationId: "HealthController_check"
          parameters: []
          responses:
            200:
              description: "The Health Check is successful"
              content:
                application/json:
                  schema:
                    type: "object"
                    properties:
                      status:
                        type: "string"
                        example: "ok"
                      info:
                        type: "object"
                        example:
                          database:
                            status: "up"
                        additionalProperties:
                          type: "object"
                          properties:
                            status:
                              type: "string"
                          additionalProperties:
                            type: "string"
                        nullable: true
                      error:
                        type: "object"
                        example: {}
                        additionalProperties:
                          type: "object"
                          properties:
                            status:
                              type: "string"
                          additionalProperties:
                            type: "string"
                        nullable: true
                      details:
                        type: "object"
                        example:
                          database:
                            status: "up"
                        additionalProperties:
                          type: "object"
                          properties:
                            status:
                              type: "string"
                          additionalProperties:
                            type: "string"
            503:
              description: "The Health Check is not successful"
              content:
                application/json:
                  schema:
                    type: "object"
                    properties:
                      status:
                        type: "string"
                        example: "error"
                      info:
                        type: "object"
                        example:
                          database:
                            status: "up"
                        additionalProperties:
                          type: "object"
                          properties:
                            status:
                              type: "string"
                          additionalProperties:
                            type: "string"
                        nullable: true
                      error:
                        type: "object"
                        example:
                          redis:
                            status: "down"
                            message: "Could not connect"
                        additionalProperties:
                          type: "object"
                          properties:
                            status:
                              type: "string"
                          additionalProperties:
                            type: "string"
                        nullable: true
                      details:
                        type: "object"
                        example:
                          database:
                            status: "up"
                          redis:
                            status: "down"
                            message: "Could not connect"
                        additionalProperties:
                          type: "object"
                          properties:
                            status:
                              type: "string"
                          additionalProperties:
                            type: "string"
      /health/liveness:
        get:
          operationId: "HealthController_liveness"
          parameters: []
          responses:
            200:
              description: "The Health Check is successful"
              content:
                application/json:
                  schema:
                    type: "object"
                    properties:
                      status:
                        type: "string"
                        example: "ok"
                      info:
                        type: "object"
                        example:
                          database:
                            status: "up"
                        additionalProperties:
                          type: "object"
                          properties:
                            status:
                              type: "string"
                          additionalProperties:
                            type: "string"
                        nullable: true
                      error:
                        type: "object"
                        example: {}
                        additionalProperties:
                          type: "object"
                          properties:
                            status:
                              type: "string"
                          additionalProperties:
                            type: "string"
                        nullable: true
                      details:
                        type: "object"
                        example:
                          database:
                            status: "up"
                        additionalProperties:
                          type: "object"
                          properties:
                            status:
                              type: "string"
                          additionalProperties:
                            type: "string"
            503:
              description: "The Health Check is not successful"
              content:
                application/json:
                  schema:
                    type: "object"
                    properties:
                      status:
                        type: "string"
                        example: "error"
                      info:
                        type: "object"
                        example:
                          database:
                            status: "up"
                        additionalProperties:
                          type: "object"
                          properties:
                            status:
                              type: "string"
                          additionalProperties:
                            type: "string"
                        nullable: true
                      error:
                        type: "object"
                        example:
                          redis:
                            status: "down"
                            message: "Could not connect"
                        additionalProperties:
                          type: "object"
                          properties:
                            status:
                              type: "string"
                          additionalProperties:
                            type: "string"
                        nullable: true
                      details:
                        type: "object"
                        example:
                          database:
                            status: "up"
                          redis:
                            status: "down"
                            message: "Could not connect"
                        additionalProperties:
                          type: "object"
                          properties:
                            status:
                              type: "string"
                          additionalProperties:
                            type: "string"
      /sapphire-pets/pet:
        get:
          operationId: "SapphirePetsController_getPets"
          parameters: []
          responses:
            200:
              description: ""
    info:
      title: "sapphire-nestjs-boilerplate"
      description: ""
      version: "1.0.0"
      contact: {}
    tags: []
    servers: []
    components:
      securitySchemes:
        cookie:
          type: "apiKey"
          in: "cookie"
          name: "ll_local"
      schemas: {}
